spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_email_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://jaragua.lmq.cloudamqp.com:5671
    username: dvkajqsi
    password: NSmLnbt0p4bnU4ch7tL5H7w08weK4dh2
    virtual-host: dvkajqsi

server:
  port: 8080